name: Multiple Jobs Demo

on: 
  push:

jobs:
  first-job: 
    runs-on: ubuntu-latest

    steps:
     - name: First Job
       run: echo "I ama the first Job"

  second-job:
    runs-on: ubuntu-latest

    steps:
      - name: Second Job
        run: echo "I am the second Job"


  
